StudienarbeitFrontend/StudienarbeitFrontend/apps/dictionary/urls.py
from django.urls import path
from . import views

app_name = 'dictionary'
urlpatterns = [
    path('', views.index, name='index'),
    path('<int:user_id>/', views.log_in, name='log_in'),
    path('create_user/', views.create_user, name='create_user'),
    path('add_user/', views.add_user, name='add_user'),
    path('remove_user/<int:u_id>/', views.remove_user, name='remove_user'),
    path('dictionary/', views.show_dictionary, name='show_dictionary'),
    path('dictionary/<int:w_id>/', views.remove_picture_from_dictionary, name="remove_picture_from_dictionary"),
    path('start_learning/', views.start_learning, name='start_learning'),
    path('select_pictures_to_upload/', views.select_pictures_to_upload, name='select_pictures_to_upload'),
    path('remove_recognized_object/<int:o_id>', views.remove_recognized_object, name='remove_recognized_object'),
    path('save_new_words/', views.save_new_words, name='save_new_words'),
    path('show_pictures_with_recognized_objects', views.show_pictures_with_recognized_objects,
         name='show_pictures_with_recognized_objects'),
    path('edit_recognized_object/<str:language>/<int:o_id>', views.edit_recognized_object, name='edit_recognized_object'),
    path('change_recognized_object/<int:o_id>/<str:language>', views.change_recognized_object,
         name='change_recognized_object'),
    path('start_learning/<int:method_nr>', views.choosed_method, name='choosed_method'),
    path('start_learning/knowing/<int:w_id>/<int:method_nr>', views.show_result_by_knowing,
         name='show_result_by_knowing'),
    path('start_learning/unknowing/<int:w_id>/<int:method_nr>', views.show_result_by_unknowing,
         name='show_result_by_unknowing'),
    path('start_learning/knowing2/<int:w_id>/<int:method_nr>', views.show_result_by_knowing2,
         name='show_result_by_knowing2'),
    path('start_learning/unknowing2/<int:w_id>/<int:method_nr>', views.show_result_by_unknowing2,
         name='show_result_by_unknowing2'),
    path('start_learning/answer/<int:w_id>/<int:xp>/<int:method_nr>', views.answer_is_given,
         name='answer_is_given'),
    path('start_learning/answer2/<int:w_id>/<int:xp>/<int:method_nr>', views.answer_is_given2,
         name='answer_is_given2'),
    ]

StudienarbeitFrontend/StudienarbeitFrontend/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('dictionary/', include('dictionary.urls')),
    path('grappelli/', include('grappelli.urls')),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

StudienarbeitFrontend/StudienarbeitFrontend/apps/dictionary/models.py
from django.db import models


class User(models.Model):
    name = models.CharField('User name', max_length=50)
    xp = models.IntegerField(default=0)
    image = models.ImageField(null=True, blank=True)


class Learnword(models.Model):
    User = models.ForeignKey(User, on_delete=models.CASCADE)
    german_word = models.CharField('german word', max_length=50)
    russian_word = models.CharField('russian word', max_length=50)
    image = models.ImageField(null=True, blank=True)
    german_pronunciation = models.FileField(null=True, blank=True, upload_to='Audio/de/')
    russian_pronunciation = models.FileField(null=True, blank=True, upload_to='Audio/ru/')


class UnsavedLearnword(models.Model):
    User = models.ForeignKey(User, on_delete=models.CASCADE)
    german_word = models.CharField('german word', max_length=50)
    russian_word = models.CharField('russian word', max_length=50)
    image = models.ImageField(null=True, blank=True)


class Training(models.Model):
    User = models.ForeignKey(User, on_delete=models.CASCADE)
    german_word = models.CharField('german word', max_length=50)
    russian_word = models.CharField('russian word', max_length=50)
    german_pronunciation = models.FileField(null=True, blank=True, upload_to='Audio/de/')
    russian_pronunciation = models.FileField(null=True, blank=True, upload_to='Audio/ru/')
    image = models.ImageField(null=True, blank=True)
    learnword_id = models.IntegerField()
    counter = models.IntegerField()

class Picture(models.Model):
    image = models.ImageField(null=True, blank=True)

StudienarbeitFrontend/StudienarbeitFrontend/apps/dictionary/views.py
import os
from django.contrib import messages
from django.http import Http404
from django.shortcuts import render, redirect
from django.urls import reverse
from imageai.Detection import ObjectDetection
from imageai.Prediction import ImagePrediction
from googletrans import Translator
from gtts import gTTS
import time

from StudienarbeitFrontend import settings
from .models import User, Learnword, Training, UnsavedLearnword, Picture


def index(request):
    user_list = User.objects.order_by('-xp')
    logged_user = get_logged_user(request.COOKIES)

    return render(request, 'dictionary/homepage.html', {'user_list': user_list, 'logged_user': logged_user})


def change_recognized_object(request, o_id, language):
    word = request.POST['word']
    unsaved_learnword = UnsavedLearnword.objects.get(id=o_id)

    if language == 'de':
        unsaved_learnword.german_word = word
        russian_word = translate_from_german_to_russian(word)
        unsaved_learnword.russian_word = russian_word
        unsaved_learnword.save()
    elif language == 'ru':
        unsaved_learnword.russian_word = word
        german_word = translate_from_russian_to_german(word)
        unsaved_learnword.german_word = german_word
        unsaved_learnword.save()

    logged_user = get_logged_user(request.COOKIES)
    unsaved_recognized_objects = UnsavedLearnword.objects.order_by('german_word')
    return render(request, 'dictionary/show_pictures_with_recognized_objects.html',
                  {'logged_user': logged_user, 'unsaved_recognized_objects': unsaved_recognized_objects})


def edit_recognized_object(request, language, o_id):
    logged_user = get_logged_user(request.COOKIES)
    unsaved_recognized_objects = UnsavedLearnword.objects.order_by('german_word')
    return render(request, 'dictionary/show_pictures_with_recognized_objects.html',
                  {'language': language, 'object_id': o_id, 'logged_user': logged_user,
                   'unsaved_recognized_objects': unsaved_recognized_objects})


def select_pictures_to_upload(request):
    logged_user = get_logged_user(request.COOKIES)
    response = render(request, 'dictionary/load_picture.html', {"logged_user": logged_user})
    UnsavedLearnword.objects.all().delete()
    if 'image_was_edit' in request.COOKIES:
        response.delete_cookie('image_was_edit')

    return response


def show_pictures_with_recognized_objects(request):
    logged_user = get_logged_user(request.COOKIES)
    pictures_to_recognize_path = settings.MEDIA_ROOT
    object_recognition_library_path = os.path.join(settings.MEDIA_ROOT, 'libraries_for_object_recognition')
    print()

    if 'image_was_edit' not in request.COOKIES:
        UnsavedLearnword.objects.all().delete()
        images_list = []
        for file in request.FILES.getlist("files"):
            Picture.objects.create(image=file)
            images_list.append(file)
        recognize_images(images_list, pictures_to_recognize_path, object_recognition_library_path, logged_user)
        unsaved_recognized_objects = UnsavedLearnword.objects.order_by('german_word')
        response = render(request, 'dictionary/show_pictures_with_recognized_objects.html',
                          {'logged_user': logged_user, 'unsaved_recognized_objects': unsaved_recognized_objects})
        response.set_cookie('image_was_edit', 'True')
        return response

    unsaved_recognized_objects = UnsavedLearnword.objects.order_by('german_word')
    return render(request, 'dictionary/show_pictures_with_recognized_objects.html',
                  {'logged_user': logged_user, 'unsaved_recognized_objects': unsaved_recognized_objects})


def recognize_images(images_list, pictures_to_recognize_path, object_recognition_library_path, logged_user):
    for image in images_list:
        image_url = os.path.join(pictures_to_recognize_path, str(image))
        prediction = ImagePrediction()
        prediction.setModelTypeAsSqueezeNet()
        path = os.path.join(object_recognition_library_path, "squeezenet_weights_tf_dim_ordering_tf_kernels.h5")
        prediction.setModelPath(path)
        prediction.setModelPath(path)
        prediction.loadModel()
        predictions, probabilities = prediction.predictImage(image_url, result_count=5)

        recognized_object_list = []
        for eachPrediction, eachProbability in zip(predictions, probabilities):
            print(eachPrediction)
            if eachProbability > 30:
                recognized_object_list.append(eachPrediction)
                print(eachPrediction, " : ", eachProbability)
        print(recognized_object_list)

        create_unsaved_learnwords(recognized_object_list, image_url, logged_user.id)


def create_unsaved_learnwords(recognized_object_list, image_url, logged_user_id):
    if len(recognized_object_list) == 0:
        recognized_object_list.append('nothing is detected')

    for recognized_object_name in recognized_object_list:
        german_word = translate_to_german(recognized_object_name)
        russian_word = translate_to_russian(recognized_object_name)
        UnsavedLearnword.objects.create(User_id=logged_user_id, german_word=german_word,
                                        russian_word=russian_word, image=image_url)


def translate_from_russian_to_german(recognized_object_name):
    translator = Translator()
    translation_de = translator.translate(recognized_object_name, dest='de', src='ru')
    german_word = translation_de.text
    return german_word


def translate_from_german_to_russian(recognized_object_name):
    translator = Translator()
    translation_de = translator.translate(recognized_object_name, dest='ru', src='de')
    german_word = translation_de.text
    return german_word


def translate_to_german(recognized_object_name):
    translator = Translator()
    translation_de = translator.translate(recognized_object_name, dest='de')
    german_word = translation_de.text
    return german_word


def translate_to_russian(recognized_object_name):
    translator = Translator()
    translation_ru = translator.translate(recognized_object_name, dest='ru')
    return translation_ru.text


def log_in(request, user_id):
    user_list = User.objects.order_by('name')

    try:
        logged_user = User.objects.get(id=user_id)
        response = render(request, 'dictionary/homepage.html', {'user_list': user_list, 'logged_user': logged_user})
        response.set_cookie('logged_user_id', logged_user.id)
    except:
        raise Http404("User was not found")

    return response


def remove_user(request, u_id):
    user = User.objects.get(id=u_id)
    user.image.delete()
    User.delete(user)
    response = redirect(reverse("dictionary:index"))
    response.delete_cookie('logged_user_id')

    return response


def create_user(request):
    return render(request, 'dictionary/create_user.html')


def add_user(request):
    name = request.POST['name']

    if User.objects.filter(name=name).exists():
        messages.warning(request, 'A user with this name already exists', extra_tags='alert')
        return redirect(reverse("dictionary:create_user"))
    else:
        try:
            if request.FILES['image']:
                image = request.FILES['image']
                User.objects.create(name=name, image=image)
        except:
            User.objects.create(name=name, image=None)

        logged_user = User.objects.get(name=name)
        response = redirect(reverse("dictionary:index"))
        response.set_cookie("logged_user_id", logged_user.id)
        return response


def show_dictionary(request):
    logged_user = get_logged_user(request.COOKIES)
    words_list = get_user_words(logged_user)

    return render(request, 'dictionary/dictionary.html',
                  {'words_list': words_list, 'logged_user': logged_user})


def choosed_method(request, method_nr):
    logged_user = get_logged_user(request.COOKIES)
    words_list = get_user_words(logged_user)
    word = None

    if len(words_list) != 0:
        word = words_list[0]

    return render(request, 'dictionary/learn.html', {'word': word, 'logged_user': logged_user, 'method_nr': method_nr})


def show_result_by_knowing(request, w_id, method_nr):
    word = Learnword.objects.get(id=w_id)
    logged_user = get_logged_user(request.COOKIES)
    return render(request, 'dictionary/show_result_by_knowing.html',
                  {'logged_user': logged_user, 'word': word, 'method_nr': method_nr})


def show_result_by_unknowing(request, w_id, method_nr):
    word = Learnword.objects.get(id=w_id)
    logged_user = get_logged_user(request.COOKIES)
    return render(request, 'dictionary/show_result_by_unknowing.html',
                  {'logged_user': logged_user, 'word': word, 'method_nr': method_nr})


def show_result_by_knowing2(request, w_id, method_nr):
    try:
        word = Training.objects.get(id=w_id)
    except:
        word = Training.objects.get(learnword_id=w_id)

    logged_user = get_logged_user(request.COOKIES)
    return render(request, 'dictionary/show_result_by_knowing2.html',
                  {'logged_user': logged_user, 'word': word, 'method_nr': method_nr})


def show_result_by_unknowing2(request, w_id, method_nr):
    try:
        word = Training.objects.get(id=w_id)
    except:
        word = Training.objects.get(learnword_id=w_id)

    logged_user = get_logged_user(request.COOKIES)
    return render(request, 'dictionary/show_result_by_unknowing2.html',
                  {'logged_user': logged_user, 'word': word, 'method_nr': method_nr})


def answer_is_given(request, w_id, xp, method_nr):
    logged_user_id = get_logged_user_id(request.COOKIES)
    logged_user = User.objects.get(id=logged_user_id)
    logged_user.xp = logged_user.xp + xp

StudienarbeitFrontend/StudienarbeitFrontend/templates/dictionary/create_user.html
{% extends 'base.html' %}
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'css/styles.css' %}"/>

{% block title %}Create user{% endblock %}
{% block content %}

    <b>Create a user account</b>
    <br><br>
  <form enctype="multipart/form-data" action="{% url 'dictionary:add_user'%}" method="post">
      {% csrf_token %}
      <div class="createUser">
          <div class="file-field input-field">
            <div class="btn">
                <span>Load your profile picture</span>
                <input type="file" name="image">
            </div>
            <div class="file-path-wrapper">
                <input class="file-path validate" type="text">
            </div>
          </div>
              {% if messages %}
                <ul class="messages" style="color:red;font-style: italic">
                    {% for message in messages %}
                        <li {% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
                    {% endfor %}
                </ul>
               {% endif %}
          <input type="text" class="validate" required placeholder="Your name" name="name">
          <button class="btn" type="submit">Save</button>
      </div>
  </form>
{% endblock %}

StudienarbeitFrontend/StudienarbeitFrontend/templates/dictionary/dictionary.html
{% extends 'base.html' %}

{% block title %}
Dictionary
{% endblock %}

{% block content %}
{% if logged_user%}
        {% if words_list %}
            <table>
                {% for w in words_list %}
                  <tr hight="50px">
                      <th style="display: inline-block;margin-right:50px">
                          <p style="margin:0px;margin-left:15px">{{w.german_word}}</p>
                          <audio src={{w.german_pronunciation.url}} controls></audio>
                      </th>
                      <th style="display: inline-block;">
                          <p style="margin:0px;margin-left:15px">{{w.russian_word}}</p>
                          <audio controls src={{w.russian_pronunciation.url}}></audio>
                      </th>
                      <th>
                          <img src={{w.image.url}} style="width:70px;length:70px" >
                      </th>
                      <th>
                          <form style="margin-top:15px" action="{% url 'dictionary:remove_picture_from_dictionary' w.id%}" method="post">
                              {% csrf_token %}
                              <button class="btn" type="submit">
                                  <i class="material-icons" type="submit">delete_forever</i>
                              </button>
                          </form>
                      </th>
                  </tr>
                {% endfor %}
            </table>

        {% else %}
        <p align="center" style="margin-top:200px">You do not have any vocabulary</p>
        {% endif %}
{% else %}
        <p>You are unlogged. Go to homepage and log in to load pictures.</p>
        <p><a href="{% url 'dictionary:index'%}">Homepage</a></p>
    {% endif %}

{% endblock %}

StudienarbeitFrontend/StudienarbeitFrontend/templates/dictionary/end_learning.html
{% extends 'base.html' %}

{% block title %}
Finish module
{% endblock %}

{% block content %}

<b>Congratulations, you repeated all the words!</b>

{% endblock %}

StudienarbeitFrontend/StudienarbeitFrontend/templates/dictionary/homepage.html
{% extends 'base.html' %}

{% block title %}
Homepage
{% endblock %}

{% block content %}
    <div class="chooseUser">

        {% if logged_user%}
            <b>You are logged in as {{logged_user.name}}</b>
        {% endif %}
        <br><br>
        <p style="font-style: italic" >Log in as ...</p>
        {% if user_list %}
            <div class="col s12" style="width:400px;">
                {% for u in user_list %}
                        <div class="row">
                            <div class="col s9">
                                <div class="col" style="margin:3px;margin-top:10px;"> <a href="{% url 'dictionary:log_in' u.id %}">{{u.name}}</a></div>
                                <div class="col" style="margin:3px;margin-top:10px;"> {{u.xp}}XP </div>
                            </div>

                            <div class="col" style="margin:5px;">
                                <form action="{% url 'dictionary:remove_user' u.id%}" method="post">
                                  {% csrf_token %}
                                  <button class="btn" type="submit">
                                      <i class="material-icons" type="submit">delete_forever</i>
                                  </button>
                                </form>
                            </div>
                        </div>
                {% endfor %}
            </div>
        {% endif %}
        <br>
        <a href="{% url 'dictionary:create_user' %}"><b> Create user </b></a>
    </div>

{% endblock %}

StudienarbeitFrontend/StudienarbeitFrontend/templates/dictionary/learn.html
{% extends 'base.html' %}

{% block title %}
Learn 1
{% endblock %}

{% block content %}
{% if word %}
    <div class="col" style="padding:10px;display:inline-block">
        <div class="z-depth-3" style="width:700px;max-height:700px;padding:10px">
            {% if method_nr == 1 %}
                <div class="row"><img src={{word.image.url}} style="width:auto;max-width:650px;height:400px"></div>
                <div class="row" style="margin:0px">
                    <p style="color: #00695c">{{word.german_word}}</p>
                    <audio controls src={{word.german_pronunciation.url}}></audio>
                </div>
            {% elif method_nr == 2 %}
                 <div class="row" style="margin:0px;color: #00695c">
                     <p style="color: #00695c">{{word.russian_word}} </p>
                     <audio controls src={{word.russian_pronunciation.url}}></audio>
                </div>
            {% endif %}

            <div class="row" style="margin:0px;margin-top:15px">
                <div class="col s6" style="text-align:left">
                    <form action="{% url 'dictionary:show_result_by_unknowing' word.id method_nr%}" method="post">
                        {% csrf_token %}
                        <button class="btn" type="submit" style="width:200px;height:auto">
                            I don't remember
                            <i class="material-icons" type="submit" style="margin-left:3px;">thumb_down</i>
                        </button>
                    </form>
                </div>

                <div class="col s6" style="text-align:right">
                    <form action="{% url 'dictionary:show_result_by_knowing' word.id method_nr%}" method="post">
                        {% csrf_token %}
                        <button class="btn" type="submit" style="width:200px;height:auto">
                            I remember
                            <i class="material-icons" type="submit" style="margin-left:5px;">thumb_up</i>
                        </button>
                    </form>
                </div>
            </div>
        </div>
    </div>

{% else %}
    <p align="center" style="margin-top:200px">You do not have any vocabulary</p>
{% endif %}
{% endblock %}

StudienarbeitFrontend/StudienarbeitFrontend/templates/dictionary/learn2.html
{% extends 'base.html' %}

{% block title %}
Learn 1
{% endblock %}

{% block content %}
{% if word%}
    <div class="col" style="padding:10px;display:inline-block">
        <div class="z-depth-3" style="width:700px;max-height:700px;padding:10px">
            {% if method_nr == 1 %}
                <div class="row"><img src={{word.image.url}} style="width:auto;max-width:650px;height:400px"></div>
                <div class="row" style="margin:0px">
                    <p style="color: #00695c;">{{word.german_word}}</p>
                    <audio src={{word.german_pronunciation.url}} controls></audio>
                </div>
            {% elif method_nr == 2 %}
                 <div class="row" style="margin:0px;margin-top:15px">
                    <p style="color: #00695c;">{{word.russian_word}}</p>
                     <audio src={{word.russian_pronunciation.url}} controls></audio>
                </div>
            {% endif %}

            <div class="row" style="margin:0px">
                <div class="col s6" style="text-align:left">
                    <form action="{% url 'dictionary:show_result_by_unknowing2' word.id method_nr%}" method="post">
                        {% csrf_token %}
                        <button class="btn" type="submit" style="width:200px;height:auto">
                            I don't remember
                            <i class="material-icons" type="submit" style="margin-left:3px;">thumb_down</i>
                        </button>
                    </form>
                </div>

                <div class="col s6" style="text-align:right">
                    <form action="{% url 'dictionary:show_result_by_knowing2' word.id method_nr%}" method="post">
                        {% csrf_token %}
                        <button class="btn" type="submit" style="width:200px;height:auto">
                            I remember
                            <i class="material-icons" type="submit" style="margin-left:5px;">thumb_up</i>
                        </button>
                    </form>
                </div>
            </div>
        </div>
    </div>

        {% else %}
        <p align="center" style="margin-top:200px">You do not have any vocabulary</p>
        {% endif %}
{% endblock %}

StudienarbeitFrontend/StudienarbeitFrontend/templates/dictionary/load_picture.html
{% extends 'base.html' %}
{% load filter_tags %}

{% block title %}
Load picture
{% endblock %}

{% block content %}
    {% if logged_user%}
            <div class="load_pictures_form">
                <form enctype="multipart/form-data" action="{% url 'dictionary:show_pictures_with_recognized_objects'%}" method="post">
                    {% csrf_token %}

                    <div class="file-field input-field">
                        <div class="btn" style="width:200px;">
                            <span>Select pictures</span>
                            <input type="file" name="files" multiple>
                        </div>
                        <div class="file-path-wrapper">
                            <input class="file-path validate" type="text">
                        </div>
                    </div>
                    <p style="color:red">Attention! Object recognition may take several minutes.</p>
                    <button class="btn" type="submit" style="width:100%">Load</button>
                </form>
            </div>

    {% else %}
        <p>You are unlogged. Go to homepage and log in to load pictures.</p>
        <p><a href="{% url 'dictionary:index'%}">Homepage</a></p>
    {% endif %}
{% endblock %}

StudienarbeitFrontend/StudienarbeitFrontend/templates/dictionary/new_words_are_successefuly_saved.html
{% extends 'base.html' %}

{% block title %}
Saved
{% endblock %}

{% block content %}

    <p style="font-size:20px">
        Your pictures were uploaded successfully :D Go to <a href="{% url 'dictionary:show_dictionary'%}">Dictionary</a>
        or to <a href="{% url 'dictionary:start_learning'%}">Learning</a> to find them again
        or <a href="{% url 'dictionary:select_pictures_to_upload'%}">upload new pictures</a>.
    </p>

{% endblock %}

StudienarbeitFrontend/StudienarbeitFrontend/templates/dictionary/show_pictures_with_recognized_objects.html
{% extends 'base.html' %}
{% load filter_tags %}

{% block title %}
Load picture
{% endblock %}

{% block content %}
    {% if logged_user%}
        <div style="display:inline-block;">
                {% for o in unsaved_recognized_objects %}
                    <div class="col" style="padding:10px;display:inline-block;">
                        <div class="z-depth-3">
                            <div class="row">
                                <img src="{{o.image.url}}" style="height:200px;max-width:300px;margin:10px">
                            </div>
                            <div class="row" style="height:50px">
                                    <div class="col">
                                        <div class="row">
                                            {% if language == "de" and o.id == object_id%}
                                                <div class="col" style="margin-left:10px;margin-top:10px;height:20px;text-decoration:line-through">{{o.german_word}}</div>
                                            {% else %}
                                                <div class="col" style="margin-left:10px;margin-top:10px;height:20px">{{o.german_word}}</div>
                                            {% endif %}
                                            <div class="col" style="margin:5px">
                                                <form action="{% url 'dictionary:edit_recognized_object' 'de' o.id%}" method="post">
                                                    {% csrf_token %}
                                                    <button class="btn" type="submit">
                                                        <i class="material-icons" type="submit">create</i>
                                                    </button>
                                                </form>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="col">
                                        <div class="row">
                                            {% if language == "ru" and o.id == object_id%}
                                                <div class="col" style="margin-left:10px;margin-top:10px;height:20px;text-decoration:line-through">{{o.russian_word}}</div>
                                            {% else %}
                                                <div class="col" style="margin-left:10px;margin-top:10px;height:20px">{{o.russian_word}}</div>
                                            {% endif %}
                                            <div class="col" style="margin:5px">
                                                <form action="{% url 'dictionary:edit_recognized_object' 'ru' o.id%}" method="post">
                                                        {% csrf_token %}
                                                    <button class="btn" type="submit">
                                                        <i class="material-icons" type="submit">create</i>
                                                    </button>
                                                    </form>
                                            </div>
                                            </div>
                                    </div>

                                    <div class="col" style="margin:5px;margin-left:25px">
                                        <form action="{% url 'dictionary:remove_recognized_object' o.id%}" method="post">
                                            {% csrf_token %}
                                            <button class="btn" type="submit">
                                                <i class="material-icons" type="submit">delete_forever</i>
                                            </button>
                                        </form>
                                 </div>
                            </div>

                            {% if language and o.id == object_id%}
                                <div class="row">
                                    <form action="{% url 'dictionary:change_recognized_object' o.id language%}" method="post" style="max-width:300px;display:inline-block">
                                        {% csrf_token %}
                                        <input type="text" class="validate" required placeholder="Your word" name="word">
                                        <button class="btn" type="submit" style="width:300px">Save</button>
                                    </form>
                                </div>
                            {% endif %}
                        </div>
                    </div>
            {% endfor %}
            <br>
            <div style="display:inline-block;">
                <p style="color:red">Attention! It may take several minutes.</p>
                <form action="{% url 'dictionary:save_new_words'%}" method="post">
                    {% csrf_token %}
                    <button class="btn" type="submit" style="width:300px">
                        Save
                    </button>
                </form>
            </div>
         </div>
    {% else %}
        <p>You are unlogged. Go to homepage and log in to load pictures.</p>
        <p><a href="{% url 'dictionary:index'%}">Homepage</a></p>
    {% endif %}
{% endblock %}